// making promises

// const prom = new Promise(); // throws the error normally , coz we need to pass a function inside it so

// ----------------------------------------------------

// lets pass the function
// const prom = new Promise(() => {}); // promise can have three state, i.e. pending, resolved, and rejected, but as of now it will pe pending, we need to pass again some argument

// ----------------------------------------------------

const prom = new Promise(() => {});
